### ISSUE TITLE
Not .NET but another interesting callstack

### ISSUE THREAD

**Issue by xiaomi7732** [xiaomi7732/StackBeauty#28]
stack trace: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at Socket.write (internal/streams/writable.js:292:11)
    at d:\Tools\VSCode\data\extensions\redhat.vscode-xml-0.19.1\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\node\ril.js:90:29
    at new Promise (<anonymous>)
    at u.write (d:\Tools\VSCode\data\extensions\redhat.vscode-xml-0.19.1\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\node\ril.js:80:16)
    at g.doWrite (d:\Tools\VSCode\data\extensions\redhat.vscode-xml-0.19.1\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\common\messageWriter.js:100:33)
    at d:\Tools\VSCode\data\extensions\redhat.vscode-xml-0.19.1\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\common\messageWriter.js:91:29

**Comment by xiaomi7732** [comment]
Actually, avoid escaping / encoding:

```shell
stack trace: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at Socket.write (internal/streams/writable.js:292:11)
    at d:\Tools\VSCode\data\extensions\redhat.vscode-xml-0.19.1\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\node\ril.js:90:29
    at new Promise (<anonymous>)
    at u.write (d:\Tools\VSCode\data\extensions\redhat.vscode-xml-0.19.1\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\node\ril.js:80:16)
    at g.doWrite (d:\Tools\VSCode\data\extensions\redhat.vscode-xml-0.19.1\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\common\messageWriter.js:100:33)
    at d:\Tools\VSCode\data\extensions\redhat.vscode-xml-0.19.1\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\common\messageWriter.js:91:29
```
